services:
  timescale_db:
    image: timescale/timescaledb:latest-pg14
    container_name: hev_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=thesis_db
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thesis_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi_backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hev_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      timescale_db:
        condition: service_healthy

  llm_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile
    container_name: hev_llm
    ports:
      - "8001:8001"

  prometheus:
    image: prom/prometheus:latest
    container_name: hev_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: hev_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./MLOps/mlruns:/mlflow/artifacts
      - ./MLOps/mlflow.db:/mlflow.db
    restart: unless-stopped 


volumes:
  timescale_data:
